version: '3.9'
services:
    client:
      image: node
      ports: ['3001:3000', '3005:9229']
      volumes: ['./client:/app']
      entrypoint: "yarn start"
      working_dir: /app
      environment:
        - NODE_OPTIONS=--openssl-legacy-provider
    server:
      image: node
      ports: ['3002:9000', '3003:9001', '3006:9229']
      volumes: ['./server:/app']
      entrypoint: "yarn dev"
      working_dir: /app
      depends_on:
        - db
    db:
      image: postgres
      env_file: .env
    adminer:
      image: adminer
      restart: always
      ports:
        - 3004:8080
